branch-defaults:
  elastic-beanstalk:
    environment: iProve-www
  master:
    environment: iProve-www
  use-npm:
    environment: iProve-www
environment-defaults:
  iProve-www:
    branch: null
    repository: null
global:
  application_name: iProve
  default_ec2_keyname: iprove-ssh
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
    64bit Amazon Linux/4.5.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-iprove
  sc: git
  workspace_type: Application
