export const NEW_RULE = 'new_rule'
export const REMOVE_RULE = 'remove_rule'
export const CHANGE_FOCUS = 'change_focus'
export const UPDATE_RULE = 'update_rule'
export const CLICK_SYMBOL = 'click_symbol'