export const NEW_RULE = 'new_rule'
export const REMOVE_RULE = 'remove_rule'
export const UPDATE_RULE = 'update_rule'
export const CHANGE_SYMBOL = 'change_symbol'
export const ADD_CONSTANT = 'add_constant'