export const NEW_RULE = 'new_rule'
export const REMOVE_RULE = 'remove_rule'
export const UPDATE_RULE = 'update_rule'
export const UPDATE_RULE_LHS = 'update_rule_lhs'
export const UPDATE_RULE_RHS = 'update_rule_rhs'
export const CHANGE_SYMBOL = 'change_symbol'